name: Deploy Terraform Infrastructure

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      GITHUB_USER: jordivilagut
      DOMAIN_NAME: farmify.app
      PROJECT_ID: a9191e2a
      PROJECT_NAME: planter
      AMI_ID: ami-01f3a9a49e4032afb
      DB_NAME: planterdb
      DB_USERNAME: planteradmin

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Generate or retrieve DB password from AWS Secrets Manager
        id: dbpass
        run: |
          SECRET_NAME="planter/db_password"

          PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id "$SECRET_NAME" \
            --query SecretString --output text 2>/dev/null || true)

          if [ -z "$PASSWORD" ]; then
            PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 20)
            aws secretsmanager create-secret \
              --name "$SECRET_NAME" \
              --secret-string "$PASSWORD"
          fi

          echo "DB_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=codefarm-terraform-states" \
            -backend-config="key=users/${GITHUB_USER}/${PROJECT_NAME}/terraform.tfstate" \
            -backend-config="region=${AWS_DEFAULT_REGION}" \
            -backend-config="encrypt=true"
        working-directory: .

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var="region=${AWS_DEFAULT_REGION}" \
            -var="project_id=${PROJECT_ID}" \
            -var="project_name=${PROJECT_NAME}" \
            -var="domain_name=${DOMAIN_NAME}" \
            -var="ami_id=${AMI_ID}" \
            -var="db_name=${DB_NAME}" \
            -var="db_user=${DB_USERNAME}" \
            -var="db_password=${DB_PASSWORD}"
        working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: .

      - name: Extract Outputs
        id: tfoutput
        run: |
          echo "ec2_instance_id=$(terraform output -raw ec2_instance_id)" >> $GITHUB_OUTPUT
          echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "app_s3_bucket=$(terraform output -raw app_s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "deployment_bucket=$(terraform output -raw deployment_s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_url=$(terraform output -raw cloudfront_distribution_url)" >> $GITHUB_OUTPUT
          echo "rds_endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT
        working-directory: .

      - name: Store deployment values in AWS Secrets Manager
        run: |
          aws secretsmanager create-secret \
            --name planter/ec2_instance_id \
            --secret-string "${{ steps.tfoutput.outputs.ec2_instance_id }}" \
            || aws secretsmanager update-secret \
            --secret-id planter/ec2_instance_id \
            --secret-string "${{ steps.tfoutput.outputs.ec2_instance_id }}"

          aws secretsmanager create-secret \
            --name planter/ec2_public_ip \
            --secret-string "${{ steps.tfoutput.outputs.ec2_public_ip }}" \
            || aws secretsmanager update-secret \
            --secret-id planter/ec2_public_ip \
            --secret-string "${{ steps.tfoutput.outputs.ec2_public_ip }}"

          aws secretsmanager create-secret \
            --name planter/rds_endpoint \
            --secret-string "${{ steps.tfoutput.outputs.rds_endpoint }}" \
            || aws secretsmanager update-secret \
            --secret-id planter/rds_endpoint \
            --secret-string "${{ steps.tfoutput.outputs.rds_endpoint }}"

          aws secretsmanager create-secret \
            --name planter/deployment_bucket \
            --secret-string "${{ steps.tfoutput.outputs.deployment_bucket }}" \
            || aws secretsmanager update-secret \
            --secret-id planter/deployment_bucket \
            --secret-string "${{ steps.tfoutput.outputs.deployment_bucket }}"
