name: Deploy Terraform Infrastructure

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      GITHUB_USER: jordivilagut
      DOMAIN_NAME: farmify.app
      PROJECT_ID: a9191e2a
      PROJECT_NAME: planter
      AMI_ID: ami-01f3a9a49e4032afb
      DB_NAME: planterdb
      DB_USERNAME: planteradmin

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Retrieve environment variables from SSM
        run: .github/scripts/get_ssm_variables.sh

      - name: Retrieve or generate DB password
        run: .github/scripts/get_or_create_db_password.sh

      - name: Terraform init
        run: ../.github/scripts/terraform_init.sh
        working-directory: infra

      - name: Terraform plan
        run: ../.github/scripts/terraform_plan.sh
        working-directory: infra

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra

      - name: Extract outputs
        id: tfoutput
        run: ../.github/scripts/terraform_extract_outputs.sh
        working-directory: infra

      - name: Store deployment values in SSM parameter store
        run: |
          .github/scripts/store_deployment_values.sh \
            "${{ steps.tfoutput.outputs.ec2_instance_id }}" \
            "${{ steps.tfoutput.outputs.ec2_public_ip }}" \
            "${{ steps.tfoutput.outputs.rds_endpoint }}" \
            "${{ steps.tfoutput.outputs.deployment_bucket }}" \
            "${{ steps.tfoutput.outputs.github_role_arn }}"
