name: Deploy Terraform Infrastructure

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      PLANTER_USER: jordivilagut
      PLANTER_PROJECT: planter

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init with Remote Backend
        run: |
          terraform init \
            -backend-config="bucket=codefarm-terraform-states" \
            -backend-config="key=users/${PLANTER_USER}/${PLANTER_PROJECT}/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"
        working-directory: .

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: .

      - name: Extract Outputs
        id: tfoutput
        run: |
          echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "s3_bucket=$(terraform output -raw s3_bucket)" >> $GITHUB_OUTPUT
          echo "cloudfront_url=$(terraform output -raw cloudfront_distribution_url)" >> $GITHUB_OUTPUT
          echo "rds_endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT
        working-directory: .

      - name: Save Outputs as Repo Secrets
        uses: gliech/create-github-secret-action@v1
        with:
          secrets: |
            PLANTER_EC2_PUBLIC_IP=${{ steps.tfoutput.outputs.ec2_public_ip }}
            PLANTER_S3_BUCKET=${{ steps.tfoutput.outputs.s3_bucket }}
            PLANTER_CLOUDFRONT_URL=${{ steps.tfoutput.outputs.cloudfront_url }}
            PLANTER_RDS_ENDPOINT=${{ steps.tfoutput.outputs.rds_endpoint }}
          token: ${{ secrets.GITHUB_TOKEN }}